__title__ = "HttpAntiDebug"
__description__ = "Python HTTP for Humans."
__version__ = "1.0.3"
__author__ = "TLSoftware"
__author_email__ = "tlsoftware.taile@gmail.com"
__license__ = "HttpAntiDebug For Tool - Vietnamese"
__copyright__ = "Copyright Tài Lê TLSoftware"